# List of supported Norwii presenters (this fork is Norwii only)
# From this config additional entries in the rules file and compiled sources are generated
# Format:
# vendorId, productId, [usb|bt], name
# Example:
# 0x0abc, 0x1234, usb, MyExample Device

0x3243, 0x0122, usb, Norwii Wireless Presenter
0x3243, 0x0382, usb, Norwii N95s BLE Presenter
0x3243, 0x03a2, bt, Norwii N95s BLE Presenter
0x3243, 0x0342, usb, Norwii N97s BLE Presenter
0x3243, 0x0352, bt, Norwii N97s BLE Presenter

